---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update Servers
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: latest

    - name: Print Host Name
      shell: echo "<h1>You are accessing my server $(hostname -f)</h1>" > /var/www/html/index.html

    - name: Set Timezone
      timezone: name=Africa/Lagos

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
